### ISSUE TITLE
Experiments: sliced experiment gets executed regardless of pre run error

### ISSUE THREAD

**Issue by fabei** [5genesis/Portal#13]
Is the experiment supposed to be run, when the slice creation fails?

![2021-07-29_14-57_portal_slicingexperr](https://user-images.githubusercontent.com/966319/127496624-f888297a-b4b8-410d-80b1-a1ea188ce516.png)

**Comment by fabei** [comment]
I'm guessing this is not a portal issue. I will investigate further.
But if you have any hints, I'd appreciate it.

**Comment by NaniteBased** [comment]
Yes, that is on the ELCM side. It is the expected behavior, in general it will report any errors but still try to do as much of the experiment as possible.

**Comment by fabei** [comment]
OK, thanks for clarifying.
